package mapping;
// Generated May 13, 2015 4:10:55 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Employe generated by hbm2java
 */
public class Employe  implements java.io.Serializable {


     private BigDecimal matricule;
     private Service service;
     private String nom;
     private String prenom;
     private Date dateEmbauche;
     private Set postes = new HashSet(0);

    public Employe() {
    }

	
    public Employe(BigDecimal matricule, Service service, String nom, String prenom, Date dateEmbauche) {
        this.matricule = matricule;
        this.service = service;
        this.nom = nom;
        this.prenom = prenom;
        this.dateEmbauche = dateEmbauche;
    }
    public Employe(BigDecimal matricule, Service service, String nom, String prenom, Date dateEmbauche, Set postes) {
       this.matricule = matricule;
       this.service = service;
       this.nom = nom;
       this.prenom = prenom;
       this.dateEmbauche = dateEmbauche;
       this.postes = postes;
    }
   
    public BigDecimal getMatricule() {
        return this.matricule;
    }
    
    public void setMatricule(BigDecimal matricule) {
        this.matricule = matricule;
    }
    public Service getService() {
        return this.service;
    }
    
    public void setService(Service service) {
        this.service = service;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public Date getDateEmbauche() {
        return this.dateEmbauche;
    }
    
    public void setDateEmbauche(Date dateEmbauche) {
        this.dateEmbauche = dateEmbauche;
    }
    public Set getPostes() {
        return this.postes;
    }
    
    public void setPostes(Set postes) {
        this.postes = postes;
    }




}


