package mapping;
// Generated May 13, 2015 4:10:55 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Projet generated by hbm2java
 */
public class Projet  implements java.io.Serializable {


     private BigDecimal idProjet;
     private String designation;
     private Date dateDebut;
     private BigDecimal budget;
     private Date dateFin;

    public Projet() {
    }

    public Projet(BigDecimal idProjet, String designation, Date dateDebut, BigDecimal budget, Date dateFin) {
       this.idProjet = idProjet;
       this.designation = designation;
       this.dateDebut = dateDebut;
       this.budget = budget;
       this.dateFin = dateFin;
    }
   
    public BigDecimal getIdProjet() {
        return this.idProjet;
    }
    
    public void setIdProjet(BigDecimal idProjet) {
        this.idProjet = idProjet;
    }
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }
    public Date getDateDebut() {
        return this.dateDebut;
    }
    
    public void setDateDebut(Date dateDebut) {
        this.dateDebut = dateDebut;
    }
    public BigDecimal getBudget() {
        return this.budget;
    }
    
    public void setBudget(BigDecimal budget) {
        this.budget = budget;
    }
    public Date getDateFin() {
        return this.dateFin;
    }
    
    public void setDateFin(Date dateFin) {
        this.dateFin = dateFin;
    }




}


