package mapping;
// Generated May 13, 2015 4:10:55 AM by Hibernate Tools 4.3.1



/**
 * ProjEmp generated by hbm2java
 */
public class ProjEmp  implements java.io.Serializable {


     private ProjEmpId id;

    public ProjEmp() {
    }

    public ProjEmp(ProjEmpId id) {
       this.id = id;
    }
   
    public ProjEmpId getId() {
        return this.id;
    }
    
    public void setId(ProjEmpId id) {
        this.id = id;
    }




}


