package mapping;
// Generated May 13, 2015 4:10:55 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Service generated by hbm2java
 */
public class Service  implements java.io.Serializable {


     private BigDecimal idServ;
     private String nomServ;
     private Set employes = new HashSet(0);

    public Service() {
    }

	
    public Service(BigDecimal idServ, String nomServ) {
        this.idServ = idServ;
        this.nomServ = nomServ;
    }
    public Service(BigDecimal idServ, String nomServ, Set employes) {
       this.idServ = idServ;
       this.nomServ = nomServ;
       this.employes = employes;
    }
   
    public BigDecimal getIdServ() {
        return this.idServ;
    }
    
    public void setIdServ(BigDecimal idServ) {
        this.idServ = idServ;
    }
    public String getNomServ() {
        return this.nomServ;
    }
    
    public void setNomServ(String nomServ) {
        this.nomServ = nomServ;
    }
    public Set getEmployes() {
        return this.employes;
    }
    
    public void setEmployes(Set employes) {
        this.employes = employes;
    }




}


